version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-net

  api:
    build: ./backend
    container_name: node-api
    environment:
      - MONGO_URL=mongodb://mongo:27017/db
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - backend-net

volumes:
  mongo-data:

networks:
  backend-net:
