version: "3.8"

services:
  api:
    build: ./backend
    container_name: api
    ports:
      - "3000:3000"
    networks:
      - appnet

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - appnet

networks:
  appnet:
